### ISSUE TITLE
Improve KPClient

### ISSUE THREAD

**Issue by rak-randers** [Randers-Kommune-Digitalisering/api-service#67]
Add error handling to KPClient and move browserless url to config

**Comment by rak-randers** [comment]
TODOs added in [kp_client.py](https://github.com/Randers-Kommune-Digitalisering/api-service/blob/st-improved-kp-client/src/kp/kp_client.py)

**Comment by rak-randers** [comment]
Added TODO in [base_api_client.py](https://github.com/Randers-Kommune-Digitalisering/api-service/blob/st-improved-kp-client/src/base_api_client.py)
Changing how lists are returned breaks nexus_flow_brugerauth job.

**Comment by st-randers** [comment]
> Added TODO in [base_api_client.py](https://github.com/Randers-Kommune-Digitalisering/api-service/blob/st-improved-kp-client/src/base_api_client.py) Changing how lists are returned breaks nexus_flow_brugerauth job.

@rak-randers Fixed i branch https://github.com/Randers-Kommune-Digitalisering/api-service/commits/st-improved-kp-client/
